azs:
- name: z1
- name: z2
- name: z3
vm_types:
- name: default
  cloud_properties:
    ephemeral_disk:
      size: 1024
      type: gp2
compilation:
  workers: 4
  network: default
  az: z1
  reuse_compilation_vms: true
  vm_type: default
networks:
- name: default
  subnets:
  - az: z1
    range: 10.244.16.0/24
    gateway: 10.244.16.1
    cloud_properties:
      name: random
  - az: z2
    range: 10.244.17.0/24
    gateway: 10.244.17.1
    cloud_properties:
      name: random
  - az: z3
    range: 10.244.18.0/24
    gateway: 10.244.18.1
    cloud_properties:
      name: random
vm_extensions:
- name: mysql-proxy-lb
  cloud_properties:
    ports:
    - host: 3306
