#!/bin/bash

set -eu

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root_dir="$( cd "${my_dir}/.." && pwd )"

"${my_dir}/deploy-bosh-lite" \
  -o "${root_dir}/operations/add-broker.yml" \
  -o "${root_dir}/operations/register-proxy-route.yml" \
  "$@"
