#!/bin/bash

set -eux

my_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
root_dir="$( cd "${my_dir}/.." && pwd )"

export BOSH_ENVIRONMENT="${BOSH_ENVIRONMENT:-192.168.50.6}"
export BOSH_DEPLOYMENT="${BOSH_DEPLOYMENT:-cf-mysql}"

pushd "${root_dir}" > /dev/null
  bosh \
    deploy \
    "${root_dir}/cf-mysql-deployment.yml" \
    -o "${root_dir}/operations/bosh-lite.yml" \
    -o "${root_dir}/operations/xenial-stemcell.yml" \
    -l "${root_dir}/bosh-lite/default-vars.yml" \
    -v "cf_mysql_external_host=p-mysql.paper-bug.pmysql.farm" \
    -v "cf_mysql_host=paper-bug.pmysql.farm" \
    -v "cf_api_url=https://api.paper-bug.pmysql.farm" \
    --no-redact \
    "$@"
popd > /dev/null
